# Generated by Django 4.1.4 on 2023-01-26 13:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=2000)),
                ('date_create', models.DateTimeField(default=datetime.datetime(2023, 1, 26, 14, 6, 30, 312879))),
                ('finished', models.BooleanField(default=False)),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
    ]
