# Generated by Django 4.1.4 on 2023-01-21 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 21, 20, 35, 27, 210521)),
        ),
        migrations.AlterField(
            model_name='workerworkingtime',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 21, 20, 35, 27, 218519)),
        ),
    ]
