# Generated by Django 4.1.4 on 2023-01-10 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='ended',
            new_name='finished',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 10, 15, 37, 49, 603361)),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.productcreate'),
        ),
        migrations.AlterField(
            model_name='project',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.servicecreate'),
        ),
        migrations.AlterField(
            model_name='project',
            name='workers',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.workerworkingtime'),
        ),
        migrations.AlterField(
            model_name='workerworkingtime',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 10, 15, 37, 49, 601436)),
        ),
    ]
