# Generated by Django 4.1.4 on 2023-01-26 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 26, 14, 25, 44, 188635)),
        ),
    ]
