# Generated by Django 4.1.4 on 2023-01-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_service_worker_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='workers',
        ),
        migrations.AddField(
            model_name='project',
            name='workers',
            field=models.ManyToManyField(related_name='projects', to='projects.worker'),
        ),
    ]
