# Generated by Django 4.1.4 on 2023-01-04 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_product_amount_productcreate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcreate',
            name='product',
        ),
        migrations.AddField(
            model_name='productcreate',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.product'),
        ),
    ]
