# Generated by Django 4.1.4 on 2023-03-31 16:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_address_alter_client_contact_person_and_more'),
        ('projects', '0006_alter_project_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Klient'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 31, 18, 28, 55, 55588), verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='project',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Zakończony'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Nazwa'),
        ),
    ]
