# Generated by Django 4.1.4 on 2023-01-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_productcreate_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='products',
            field=models.ManyToManyField(related_name='projects', to='projects.productcreate'),
        ),
    ]
