# Generated by Django 4.1.4 on 2023-01-04 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcreate',
            name='price',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.CreateModel(
            name='ServiceCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, max_length=10)),
                ('price', models.FloatField(default=0, max_length=10)),
                ('service', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.service')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='services',
            field=models.ManyToManyField(related_name='projects', to='projects.servicecreate'),
        ),
    ]
