# Generated by Django 4.1.4 on 2023-01-04 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_productcreate_price_servicecreate_project_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerWorkingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_amount', models.PositiveIntegerField(default=0, max_length=10)),
                ('price_per_hour', models.FloatField(default=0, max_length=10)),
                ('worker', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.worker')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='workers',
            field=models.ManyToManyField(related_name='projects', to='projects.workerworkingtime'),
        ),
    ]
