version: '3.4'

services:

  django-app:
    image: accounting-app:latest
    container_name: accounting-app
    build:
      context: .
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./:/app/
    command: /app/run_dev_server.sh

  postgres:
    image: postgres:latest
    container_name: accounting-db
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./temp/postgres:/var/lib/postgresql/data
      - ./docker/init-postgres.sql:/docker-entrypoint-initdb.d/01-setup.sql:ro
