# Generated by Django 4.1.4 on 2022-12-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='steel_type',
            field=models.CharField(choices=[('STEEL_1', 'STEEL_1'), ('STEEL_2', 'STEEL_2'), ('STEEL_3', 'STEEL_3')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kilos', 'kilos'), ('tones', 'tones')], help_text='unit of the product.', max_length=10),
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
