# Generated by Django 4.1.4 on 2022-12-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_steel_type_alter_product_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='no_of_units',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
