# Generated by Django 4.1.4 on 2022-12-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_no_of_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='steel_type',
            field=models.CharField(choices=[('304', '304'), ('316', '316'), ('321', '321')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'kg'), ('mb', 'mb'), ('szt.', 'szt.')], help_text='unit of the product.', max_length=10),
        ),
    ]
