# Generated by Django 4.1.4 on 2022-12-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_steel_type_alter_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='no_of_units',
            field=models.FloatField(default=0, null=True),
        ),
    ]
