# Generated by Django 4.1.4 on 2022-12-19 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_product_no_of_units'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='no_of_units',
            new_name='amount',
        ),
    ]
