# Generated by Django 4.1.4 on 2023-01-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('address', models.CharField(max_length=300)),
                ('contact_person', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=240)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
