# Generated by Django 4.1.4 on 2023-01-26 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_date_create'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerforproject',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workerforproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='projects.project'),
        ),
    ]
