# Generated by Django 4.1.4 on 2023-01-26 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_alter_workerforproject_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerforproject',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
