# Generated by Django 4.1.4 on 2023-03-31 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_client_alter_project_date_create_and_more'),
        ('products', '0002_rename_productcreate_productforproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default=0, max_length=255, verbose_name='Opis / uwagi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nazwa produktu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='steel_type',
            field=models.CharField(choices=[('304', '304'), ('316', '316'), ('321', '321')], max_length=10, verbose_name='Gatunek stali'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'kg'), ('mb', 'mb'), ('szt.', 'szt.')], help_text='jednostka', max_length=10, verbose_name='Jednostka'),
        ),
        migrations.AlterField(
            model_name='productforproject',
            name='amount',
            field=models.FloatField(default=0, max_length=10, verbose_name='Ilość'),
        ),
        migrations.AlterField(
            model_name='productforproject',
            name='price',
            field=models.FloatField(default=0, max_length=10, verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='productforproject',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Wybierz produkt'),
        ),
        migrations.AlterField(
            model_name='productforproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Wybierz projekt'),
        ),
    ]
