# Generated by Django 4.1.4 on 2023-03-31 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default=0, max_length=255, verbose_name='Opis / uwagi'),
            preserve_default=False,
        ),
    ]
